return {
        ["Windset Totem"] = { Price = "2000", Type = "Item" },
        ["Tidebreaker"] = { Price = "80000", Type = "Item" },
        ["Intermediate Oxygen Tank"] = { Price = "10000", Type = "Item" },
        ["Flippers"] = { Price = "9000", Type = "Item" },
        ["Red Energy Crystal"] = { Price = "25", Type = "Fish" },
        ["Basic Diving Gear"] = { Price = "3000", Type = "Item" },
        ["Crossbow Base"] = { Price = "inf", Type = "Item" },
        ["Water Bubble"] = { Price = "25000", Type = "Item" },
        ["Smokescreen Totem"] = { Price = "2000", Type = "Item" },
        ["Poseidon Wrath Totem"] = { Price = "1500000", Type = "Item" },
        ["Zeus Storm Totem"] = { Price = "1500000", Type = "Item" },
        ["Advanced Diving Gear"] = { Price = "15000", Type = "Item" },
        ["GPS"] = { Price = "100", Type = "Item" },
        ["Glimmerfin Suit Lvl 2"] = { Price = "7500", Type = "Item" },
        ["Lunar Thread"] = { Price = "inf", Type = "Item" },
        ["Aurora Totem"] = { Price = "500000", Type = "Item" },
        ["Beginner Oxygen Tank"] = { Price = "3500", Type = "Item" },
        ["Firework"] = { Price = "130", Type = "Item" },
        ["Quality Bait Crate"] = { Price = "525", Type = "Fish" },
        ["Avalanche Totem"] = { Price = "150000", Type = "Item" },
        ["Conception Conch"] = { Price = "444", Type = "Item" },
        ["Bait Crate"] = { Price = "120", Type = "Fish" },
        ["Advanced Oxygen Tank"] = { Price = "25000", Type = "Item" },
        ["Glimmerfin Suit Lvl 3"] = { Price = "7500", Type = "Item" },
        ["Tempest Totem"] = { Price = "2000", Type = "Item" },
        ["Common Crate"] = { Price = "128", Type = "Fish" },
        ["Blizzard Totem"] = { Price = "275000", Type = "Item" },
        ["Crab Cage"] = { Price = "45", Type = "Item" },
        ["Carbon Crate"] = { Price = "490", Type = "Fish" },
        ["Coral Geode"] = { Price = "600", Type = "Fish" },
        ["Festive Bait Crate"] = { Price = "1150", Type = "Fish" },
        ["TNT"] = { Price = "inf", Type = "Item" },
        ["Volcanic Geode"] = { Price = "600", Type = "Fish" },
        ["Glimmerfin Suit Lvl 1"] = { Price = "7500", Type = "Item" },
        ["Eclipse Totem"] = { Price = "250000", Type = "Item" },
        ["Basic Oxygen Tank"] = { Price = "1000", Type = "Item" },
        ["Fish Radar"] = { Price = "8000", Type = "Item" },
        ["Glider"] = { Price = "900", Type = "Item" },
        ["Pickaxe"] = { Price = "5000", Type = "Item" },
        ["Meteor Totem"] = { Price = "75000", Type = "Item" },
        ["Witches Ingredient"] = { Price = "10000", Type = "Item" },
        ["Sundial Totem"] = { Price = "2000", Type = "Item" },
        ["Winter Cloak"] = { Price = "7500", Type = "Item" },
        ["Advanced Glider"] = { Price = "2500", Type = "Item" },
        ["Super Flippers"] = { Price = "30000", Type = "Item" },
}
